
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvzdukthkxozmmbbtnrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2emR1a3Roa3hvem1tYmJ0bnJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjM5OTYsImV4cCI6MjA2MDEzOTk5Nn0.DUOHIB6gyC6ppivVovP8VK5SRbop2YAU95uxuYAJdd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
